cc_library(
    name = "folder",
    srcs = [],
    hdrs = [
        "folder.h",
    ],
)

cc_library(
    name = "message",
    srcs = ["message.cc"],
    hdrs = ["message.h"],
    deps = [
        ":folder",
    ],
)
